/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['h1[_ngcontent-%COMP%]{\r\n   color:green;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC91c2Vycy91c2VyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC91c2Vycy91c2VyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
