/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './user.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './user.component';
const styles_UserComponent:any[] = [i0.styles];
export const RenderType_UserComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_UserComponent,data:{}});
export function View_UserComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['User Component']))],(null as any),(null as any));
}
export function View_UserComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_UserComponent_0,
      RenderType_UserComponent)),i1.ɵdid(49152,(null as any),0,i2.UserComponent,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const UserComponentNgFactory:i1.ComponentFactory<i2.UserComponent> = i1.ɵccf('ng-component',
    i2.UserComponent,View_UserComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC91c2Vycy91c2VyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9WaXR0YWwvUE9Dcy9Bbmd1bGFyNC9hbmd1bGFyNC1idWlsZC1wcm9qZWN0LXN0ci9zcmMvYXBwL3VzZXJzL3VzZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC91c2Vycy91c2VyLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC91c2Vycy91c2VyLmNvbXBvbmVudC50cy5Vc2VyQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgxPlVzZXIgQ29tcG9uZW50PC9oMT4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFJO2FBQUE7OztvQkNBSjtNQUFBOzhCQUFBLFVBQUE7TUFBQTs7OyJ9
