/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './user.module';
import * as i2 from './user.component.ngfactory';
import * as i3 from '@angular/common';
import * as i4 from '@angular/router';
import * as i5 from './user-routing-module';
import * as i6 from './user.component';
export const UserModuleNgFactory:i0.NgModuleFactory<i1.UserModule> = i0.ɵcmf(i1.UserModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.UserComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(4608,i3.NgLocalization,i3.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,
              i3.CommonModule,i3.CommonModule,([] as any[])),i0.ɵmpd(512,i4.RouterModule,
              i4.RouterModule,[[2,i4.ɵa],[2,i4.Router]]),i0.ɵmpd(512,i5.UserRoutingModule,
              i5.UserRoutingModule,([] as any[])),i0.ɵmpd(512,i1.UserModule,i1.UserModule,
              ([] as any[])),i0.ɵmpd(1024,i4.ROUTES,() => {
            return [[{path:'',component:i6.UserComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC91c2Vycy91c2VyLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9WaXR0YWwvUE9Dcy9Bbmd1bGFyNC9hbmd1bGFyNC1idWlsZC1wcm9qZWN0LXN0ci9zcmMvYXBwL3VzZXJzL3VzZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
