/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './user-routing-module';
import * as i2 from './user.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from './user.component';
export const UserRoutingModuleNgFactory:i0.NgModuleFactory<i1.UserRoutingModule> = i0.ɵcmf(i1.UserRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.UserComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,[[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,
              i1.UserRoutingModule,i1.UserRoutingModule,([] as any[])),i0.ɵmpd(1024,
              i3.ROUTES,() => {
                return [[{path:'',component:i4.UserComponent}]];
              },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC91c2Vycy91c2VyLXJvdXRpbmctbW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1ZpdHRhbC9QT0NzL0FuZ3VsYXI0L2FuZ3VsYXI0LWJ1aWxkLXByb2plY3Qtc3RyL3NyYy9hcHAvdXNlcnMvdXNlci1yb3V0aW5nLW1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
