/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app-routing-module';
import * as i2 from './home.component.ngfactory';
import * as i3 from '@angular/router';
import * as i4 from '@angular/common';
import * as i5 from './home.component';
export const AppRoutingModuleNgFactory:i0.NgModuleFactory<i1.AppRoutingModule> = i0.ɵcmf(i1.AppRoutingModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.HomeComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i3.ActivatedRoute,i3.ɵf,[i3.Router]),i0.ɵmpd(4608,i3.NoPreloading,
              i3.NoPreloading,([] as any[])),i0.ɵmpd(6144,i3.PreloadingStrategy,(null as any),
              [i3.NoPreloading]),i0.ɵmpd(135680,i3.RouterPreloader,i3.RouterPreloader,
              [i3.Router,i0.NgModuleFactoryLoader,i0.Compiler,i0.Injector,i3.PreloadingStrategy]),
          i0.ɵmpd(4608,i3.PreloadAllModules,i3.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,
              i0.NgProbeToken,() => {
                return [i3.ɵb()];
              },([] as any[])),i0.ɵmpd(4608,i3.ɵg,i3.ɵg,[i0.Injector]),i0.ɵmpd(5120,
              i0.APP_INITIALIZER,(p0_0:any) => {
                return [i3.ɵh(p0_0)];
              },[i3.ɵg]),i0.ɵmpd(5120,i3.ROUTER_INITIALIZER,i3.ɵi,[i3.ɵg]),i0.ɵmpd(5120,
              i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
                return [p0_0];
              },[i3.ROUTER_INITIALIZER]),i0.ɵmpd(1024,i3.ɵa,i3.ɵd,[[3,i3.Router]]),
          i0.ɵmpd(512,i3.UrlSerializer,i3.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i3.ChildrenOutletContexts,i3.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,
              i3.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i4.LocationStrategy,
              i3.ɵc,[i4.PlatformLocation,[2,i4.APP_BASE_HREF],i3.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i4.Location,i4.Location,[i4.LocationStrategy]),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i3.ROUTES,() => {
            return [[{path:'',component:i5.HomeComponent},{path:'users',loadChildren:'./users/user.module#UserModule'}]];
          },([] as any[])),i0.ɵmpd(1024,i3.Router,i3.ɵe,[i0.ApplicationRef,i3.UrlSerializer,
              i3.ChildrenOutletContexts,i4.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i3.ROUTES,i3.ROUTER_CONFIGURATION,[2,i3.UrlHandlingStrategy],
              [2,i3.RouteReuseStrategy]]),i0.ɵmpd(512,i3.RouterModule,i3.RouterModule,
              [[2,i3.ɵa],[2,i3.Router]]),i0.ɵmpd(512,i1.AppRoutingModule,i1.AppRoutingModule,
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC9hcHAtcm91dGluZy1tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC9hcHAtcm91dGluZy1tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
