/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './home.component';
const styles_HomeComponent:any[] = ([] as any[]);
export const RenderType_HomeComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_HomeComponent,data:{}});
export function View_HomeComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['Home Component']))],(null as any),(null as any));
}
export function View_HomeComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'ng-component',
      ([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,
      RenderType_HomeComponent)),i0.ɵdid(49152,(null as any),0,i1.HomeComponent,([] as any[]),
      (null as any),(null as any))],(null as any),(null as any));
}
export const HomeComponentNgFactory:i0.ComponentFactory<i1.HomeComponent> = i0.ɵccf('ng-component',
    i1.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC9ob21lLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9WaXR0YWwvUE9Dcy9Bbmd1bGFyNC9hbmd1bGFyNC1idWlsZC1wcm9qZWN0LXN0ci9zcmMvYXBwL2hvbWUuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvYW5ndWxhcjQtYnVpbGQtcHJvamVjdC1zdHIvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cy5Ib21lQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9WaXR0YWwvUE9Dcy9Bbmd1bGFyNC9hbmd1bGFyNC1idWlsZC1wcm9qZWN0LXN0ci9zcmMvYXBwL2hvbWUuY29tcG9uZW50LnRzLkhvbWVDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8aDE+SG9tZSBDb21wb25lbnQ8L2gxPiIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBSTthQUFBOzs7b0JDQUo7TUFBQTs4QkFBQSxVQUFBO01BQUE7OzsifQ==
