/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvQU5HVUxBUjIwMS9iaXRidWNrZXQvYW5ndWxhcjQtY291cnNlLW1hdGVyaWFsMi9zcmMvdGhlbWUvc2Nzcy9tb2R1bGVzL19idXR0b24uc2Nzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9WaXR0YWwvUE9Dcy9Bbmd1bGFyNC9BTkdVTEFSMjAxL2JpdGJ1Y2tldC9hbmd1bGFyNC1jb3Vyc2UtbWF0ZXJpYWwyL3NyYy90aGVtZS9zY3NzL21vZHVsZXMvX2J1dHRvbi5zY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
