/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvQU5HVUxBUjIwMS9iaXRidWNrZXQvYW5ndWxhcjQtY291cnNlLW1hdGVyaWFsMi9zcmMvdGhlbWUvc2Nzcy9tb2R1bGVzL19jbGVhcmZpeC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1ZpdHRhbC9QT0NzL0FuZ3VsYXI0L0FOR1VMQVIyMDEvYml0YnVja2V0L2FuZ3VsYXI0LWNvdXJzZS1tYXRlcmlhbDIvc3JjL3RoZW1lL3Njc3MvbW9kdWxlcy9fY2xlYXJmaXguc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
