/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvQU5HVUxBUjIwMS9iaXRidWNrZXQvYW5ndWxhcjQtY291cnNlLW1hdGVyaWFsMi9zcmMvdGhlbWUvc2Nzcy9tb2R1bGVzL19mb250LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvQU5HVUxBUjIwMS9iaXRidWNrZXQvYW5ndWxhcjQtY291cnNlLW1hdGVyaWFsMi9zcmMvdGhlbWUvc2Nzcy9tb2R1bGVzL19mb250LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
