/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './_colors.scss.shim.ngstyle';
import * as i1 from './_button.scss.shim.ngstyle';
import * as i2 from './_clearfix.scss.shim.ngstyle';
import * as i3 from './_font.scss.shim.ngstyle';
import * as i4 from './_input.scss.shim.ngstyle';
import * as i5 from './_media-query.scss.shim.ngstyle';
import * as i6 from './_transition.scss.shim.ngstyle';
import * as i7 from './_wrapper.scss.shim.ngstyle';
export const styles:any[] = ['// \r\n// \r\n\r\n// \r\n// \r\n// \r\n// \r\n//',i0.styles,
    i1.styles,i2.styles,i3.styles,i4.styles,i5.styles,i6.styles,i7.styles];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovVml0dGFsL1BPQ3MvQW5ndWxhcjQvQU5HVUxBUjIwMS9iaXRidWNrZXQvYW5ndWxhcjQtY291cnNlLW1hdGVyaWFsMi9zcmMvdGhlbWUvc2Nzcy9tb2R1bGVzL3N0eWxlcy5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1ZpdHRhbC9QT0NzL0FuZ3VsYXI0L0FOR1VMQVIyMDEvYml0YnVja2V0L2FuZ3VsYXI0LWNvdXJzZS1tYXRlcmlhbDIvc3JjL3RoZW1lL3Njc3MvbW9kdWxlcy9zdHlsZXMuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
